version: "3"
services:
  nextjs:
    build:
      context: ./frontend # Next.jsアプリケーションのパスを指定
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Next.jsアプリケーションのパスを指定
    depends_on:
      - mysql

  rails:
    build:
      context: ./backend # Railsアプリケーションのパスを指定
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app # Railsアプリケーションのパスを指定
    depends_on:
      - mysql
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
